
-- Table: PPI_SCREEN_OFF
CREATE TABLE PPI_SCREEN_OFF ( 
    IORDEM     INTEGER         NOT NULL
                               CONSTRAINT CKC_IORDEM_PPI_SCRE CHECK ( IORDEM BETWEEN '1' AND '10' ),
    TXENDERECO VARCHAR( 100 )  NOT NULL,
    ISEGUNDOS  INTEGER         NOT NULL
                               DEFAULT '15'
                               CONSTRAINT CKC_ISEGUNDOS_PPI_SCRE CHECK ( ISEGUNDOS BETWEEN '1' AND '30' ),
    CONSTRAINT PK_PPI_SCREEN_OFF PRIMARY KEY ( IORDEM ) 
);


-- Table: PPI_GROUP
CREATE TABLE PPI_GROUP ( 
    IDPPIGROUP            INTEGER         NOT NULL
                                          CONSTRAINT CKC_IDPPIGROUP_PPI_GROU CHECK ( IDPPIGROUP BETWEEN '1001' AND '9999' ),
    TXDESCRICAO           VARCHAR( 100 )  NOT NULL,
    TXOBJETIVO            VARCHAR( 200 )  NOT NULL,
    DTINCLUSAO            DATE            NOT NULL,
    DHINICIOPUBLICACAO    DATETIME        NOT NULL,
    DHFINALPUBLICACO      DATETIME        NOT NULL,
    FLAGPESQUISAALEATORIA BOOLEAN         NOT NULL
                                          DEFAULT 'false',
    FLAGJOGOPERGUNTAS     BOOLEAN         NULL
                                          DEFAULT 'false',
    CONSTRAINT PK_PPI_GROUP PRIMARY KEY ( IDPPIGROUP ) 
);


-- Table: PPI_SCREEN_ON
CREATE TABLE PPI_SCREEN_ON ( 
    IDPPIGROUP INTEGER         NOT NULL
                               CONSTRAINT 'CKC_IDPPIGROUP_PPI_SCRE' CHECK ( IDPPIGROUP BETWEEN '1001' AND '9999' ) 
                               REFERENCES PPI_GROUP ( IDPPIGROUP ) ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION,
    IORDEM     INTEGER         NOT NULL
                               CONSTRAINT 'CKC_IORDEM_PPI_SCRE' CHECK ( IORDEM BETWEEN '1' AND '10' ),
    TXENDERECO VARCHAR( 100 )  NOT NULL,
    ISEGUNDOS  INTEGER         NOT NULL
                               CONSTRAINT 'CKC_ISEGUNDOS_PPI_SCRE' CHECK ( ISEGUNDOS BETWEEN '1' AND '10' ) 
                               DEFAULT '5',
    CONSTRAINT 'PK_PPI_SCREEN_ON' PRIMARY KEY ( IORDEM ) 
);


-- Table: PPI_QUESTION_GROUP
CREATE TABLE PPI_QUESTION_GROUP ( 
    IDPPIGROUP INTEGER NOT NULL
                       CONSTRAINT CKC_IDPPIGROUP_PPI_QUES CHECK ( IDPPIGROUP BETWEEN '1001' AND '9999' ),
    IDQUESTAO  INTEGER NOT NULL,
    IORDEM     INTEGER NULL,
    CONSTRAINT PK_PPI_QUESTION_GROUP PRIMARY KEY ( IDPPIGROUP, IDQUESTAO ) 
);


-- Table: PPI_QUESTION
CREATE TABLE PPI_QUESTION ( 
    IDQUESTAO INTEGER         NOT NULL,
    TXQUESTAO VARCHAR( 300 )  NOT NULL,
    CONSTRAINT PK_PPI_QUESTION PRIMARY KEY ( IDQUESTAO ) 
);


-- Table: PPI_QUESTION_ALTERNATIVE
CREATE TABLE PPI_QUESTION_ALTERNATIVE ( 
    IDALTERNATIVA INTEGER         NOT NULL,
    IDQUESTAO     INTEGER         NOT NULL,
    TXALTERNATIVA VARCHAR( 200 )  NULL,
    CONSTRAINT PK_PPI_QUESTION_ALTERNATIVE PRIMARY KEY ( IDALTERNATIVA, IDQUESTAO ) 
);


-- Table: PPI_QUESTION_ALTERNATIVE_CORREC
CREATE TABLE PPI_QUESTION_ALTERNATIVE_CORREC ( 
    IDALTERNATIVA INTEGER NOT NULL,
    IDQUESTAO     INTEGER NOT NULL,
    CONSTRAINT PK_PPI_QUESTION_ALTERNATIVE_CO PRIMARY KEY ( IDALTERNATIVA, IDQUESTAO ) 
);


-- Table: PPI_PARTICIPANT
CREATE TABLE PPI_PARTICIPANT ( 
    TXNOME           INTEGER  NOT NULL,
    DTHRPARTICIPACAO DATETIME NOT NULL,
    IDPARTICIPANTE   INTEGER  NOT NULL,
    CONSTRAINT PK_PPI_PARTICIPANT PRIMARY KEY ( IDPARTICIPANTE ) 
);


-- Table: PPI_CONFIG_PRIZE
CREATE TABLE PPI_CONFIG_PRIZE ( 
    IDPPIGROUP INTEGER      NOT NULL
                            CONSTRAINT 'CKC_IDPPIGROUP_PPI_CONF' CHECK ( IDPPIGROUP BETWEEN '1001' AND '9999' ) 
                            REFERENCES PPI_GROUP ( IDPPIGROUP ) ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION,
    CHAVE      INTEGER      NOT NULL,
    VALOR      CHAR( 300 ),
    CONSTRAINT 'PK_PPI_CONFIG_PRIZE' PRIMARY KEY ( IDPPIGROUP, CHAVE ) 
);


-- Table: PPI_PARTICIPANT_QUESTION_ALTERN
CREATE TABLE PPI_PARTICIPANT_QUESTION_ALTERN ( 
    IDALTERNATIVA  INTEGER  NOT NULL,
    IDQUESTAO      INTEGER  NOT NULL,
    IDPARTICIPANTE INTEGER  NOT NULL,
    DTHRRESPOSTA   DATETIME NOT NULL,
    CONSTRAINT 'PK_PPI_PARTICIPANT_QUESTION_AL' PRIMARY KEY ( IDALTERNATIVA, IDQUESTAO, IDPARTICIPANTE ) 
);


-- Index: IDXU_GROUPQUES2
CREATE INDEX IDXU_GROUPQUES2 ON PPI_QUESTION_ALTERNATIVE_CORREC ( 
    IDALTERNATIVA,
    IDQUESTAO 
);

