
-- Table: PPI_GROUP
CREATE TABLE PPI_GROUP ( 
    IDPPIGROUP            INTEGER         NOT NULL
                                          CONSTRAINT CKC_IDPPIGROUP_PPI_GROU CHECK ( IDPPIGROUP BETWEEN '1001' AND '9999' ),
    TXDESCRICAO           VARCHAR( 100 )  NOT NULL,
    TXOBJETIVO            VARCHAR( 200 )  NOT NULL,
    DTINCLUSAO            DATE            NOT NULL,
    DHINICIOPUBLICACAO    DATETIME        NOT NULL,
    DHFINALPUBLICACO      DATETIME        NOT NULL,
    FLAGPESQUISAALEATORIA BOOLEAN         NOT NULL
                                          DEFAULT 'false',
    CONSTRAINT PK_PPI_GROUP PRIMARY KEY ( IDPPIGROUP ) 
);


-- Table: PPI_SCREEN_OFF
CREATE TABLE PPI_SCREEN_OFF ( 
    IORDEM     INTEGER         NOT NULL
                               CONSTRAINT CKC_IORDEM_PPI_SCRE CHECK ( IORDEM BETWEEN '1' AND '10' ),
    TXENDERECO VARCHAR( 100 )  NOT NULL,
    ISEGUNDOS  INTEGER         NOT NULL
                               DEFAULT '15'
                               CONSTRAINT CKC_ISEGUNDOS_PPI_SCRE CHECK ( ISEGUNDOS BETWEEN '1' AND '30' ),
    CONSTRAINT PK_PPI_SCREEN_OFF PRIMARY KEY ( IORDEM ) 
);


-- Table: PPI_SCREEN_ON
CREATE TABLE PPI_SCREEN_ON ( 
    IDPPIGROUP INTEGER         NOT NULL
                               CONSTRAINT 'CKC_IDPPIGROUP_PPI_SCRE' CHECK ( IDPPIGROUP BETWEEN '1001' AND '9999' ),
    IORDEM     INTEGER         NOT NULL
                               CONSTRAINT 'CKC_IORDEM_PPI_SCRE' CHECK ( IORDEM BETWEEN '1' AND '10' ),
    TXENDERECO VARCHAR( 100 )  NOT NULL,
    ISEGUNDOS  INTEGER         NOT NULL
                               CONSTRAINT 'CKC_ISEGUNDOS_PPI_SCRE' CHECK ( ISEGUNDOS BETWEEN '1' AND '10' ) 
                               DEFAULT '5',
    CONSTRAINT 'PK_PPI_SCREEN_ON' PRIMARY KEY ( IORDEM ),
    FOREIGN KEY ( IDPPIGROUP ) REFERENCES PPI_GROUP ( IDPPIGROUP ) ON DELETE RESTRICT
                                                                       ON UPDATE RESTRICT 
);

